Repository YAPP-Github/21st-Web-Team-2-FE, pull requests merged in 2023-01, with the labels that each got.

#27 [feat] 디자인 시스템 구현
  .github/CODEOWNERS
  .prettierrc.js
  .storybook/preview.js
  package-lock.json
  package.json
  src/components/Example/Example.stories.tsx
  src/components/Example/Example.style.tsx
  src/components/Example/Example.tsx
  src/components/Example/index.tsx
  src/pages/_app.tsx
  src/styles/common.css
  src/styles/reset.css
  src/styles/theme.ts
Labels: 🐛bug, ✨ feature

#28 [feat] 아이콘 컴포넌트 구현 (SVG ICON)
  .gitignore
  .storybook/main.js
  next.config.js
  package-lock.json
  package.json
  src/assets/icon/arrow_down.svg
  src/assets/icon/arrow_right.svg
  src/assets/icon/arrow_up.svg
  src/assets/icon/clap.svg
  src/assets/icon/create.svg
  src/assets/icon/delete.svg
  src/assets/icon/emoji_bubble.svg
  src/assets/icon/emoji_career.svg
  src/assets/icon/emoji_computer.svg
  src/assets/icon/emoji_hands_up.svg
  src/assets/icon/emoji_paint.svg
  src/assets/icon/emoji_paper.svg
  src/assets/icon/emoji_thumbs_up.svg
  src/assets/icon/image.svg
  src/assets/icon/index.tsx
  src/assets/icon/more.svg
  src/assets/icon/search.svg
  src/assets/icon/share.svg
  src/assets/icon/vote.svg
  src/components/common/Icon/Icon.stories.tsx
  src/components/common/Icon/Icon.tsx
  src/components/common/Icon/index.tsx
  src/pages/index.stories.tsx
  src/pages/index.test.tsx
  src/pages/index.tsx
  src/styles/theme.ts
  src/types/svg.d.ts
Labels: ✨ feature

#22 [feat] 태그 컴포넌트 구현
  __mocks__/MockIcon.jsx
  jest.config.js
  src/assets/icon/index.tsx
  src/assets/icon/x.svg
  src/components/common/TagList/TagList.stories.tsx
  src/components/common/TagList/TagList.styles.tsx
  src/components/common/TagList/TagList.test.tsx
  src/components/common/TagList/TagList.tsx
  src/components/common/TagList/TagListItem/TagListItem.stories.tsx
  src/components/common/TagList/TagListItem/TagListItem.styles.tsx
  src/components/common/TagList/TagListItem/TagListItem.test.tsx
  src/components/common/TagList/TagListItem/TagListItem.tsx
  src/components/common/TagList/TagListItem/index.tsx
  src/components/common/TagList/index.tsx
  src/styles/common.css
Labels: ✨ feature

#32 [feat] CommentForm 기능 구현
  src/components/CommentForm/CommentForm.stories.tsx
  src/components/CommentForm/CommentForm.styles.tsx
  src/components/CommentForm/CommentForm.tsx
  src/components/CommentForm/index.tsx
  src/styles/common.css
  src/styles/theme.ts
Labels: ✨ feature

#33 [feat] TopicCard 텍스트만 구현
  src/components/TopicCard/SelectOption/SelectOption.stories.tsx
  src/components/TopicCard/SelectOption/SelectOption.style.tsx
  src/components/TopicCard/SelectOption/SelectOption.tsx
  src/components/TopicCard/SelectOption/index.tsx
  src/components/TopicCard/TopicCard.stories.tsx
  src/components/TopicCard/TopicCard.style.tsx
  src/components/TopicCard/TopicCard.tsx
  src/components/TopicCard/index.tsx
  src/types/Member.ts
  src/types/Topic.ts
Labels: ✨ feature

#37 [feat] grid system 및 기본 레이아웃 구현
  src/components/DefaultLayout/DefaultLayout.stories.tsx
  src/components/DefaultLayout/DefaultLayout.tsx
  src/components/DefaultLayout/index.tsx
  src/components/common/Grid/Grid.stories.tsx
  src/components/common/Grid/Grid.styles.tsx
  src/components/common/Grid/Grid.tsx
  src/components/common/Grid/GridContainer.styles.tsx
  src/components/common/Grid/GridContainer.tsx
  src/components/common/Grid/index.tsx
Labels: ✨ feature

#39 [feat] CommentList 기능 구현
  __mocks__/data/comment.ts
  src/components/CommentList/CommentList.stories.tsx
  src/components/CommentList/CommentList.style.tsx
  src/components/CommentList/CommentList.tsx
  src/components/CommentList/CommentListItem/CommentListItem.stories.tsx
  src/components/CommentList/CommentListItem/CommentListItem.styles.tsx
  src/components/CommentList/CommentListItem/CommentListItem.tsx
  src/components/CommentList/CommentListItem/index.tsx
  src/components/CommentList/index.tsx
  src/styles/reset.css
  src/types/Comment.ts
Labels: ✨ feature

#40 [refactor] CommentList 피드백 적용하지 않고 merge 되어 해당 PR 로 작업 수정
  src/components/CommentList/CommentList.stories.tsx
  src/components/CommentList/CommentList.style.tsx
  src/components/CommentList/CommentList.tsx
  src/components/CommentList/CommentListItem/CommentListItem.stories.tsx
  src/components/CommentList/CommentListItem/CommentListItem.styles.tsx
Labels: ⚙️ chore, ♻️ refactor

#42 [feat] SideMenu 구현
  src/components/SideMenu/SideMenu.stories.tsx
  src/components/SideMenu/SideMenu.styles.tsx
  src/components/SideMenu/SideMenu.tsx
  src/components/SideMenu/SideMenuItem/SideMenuItem.stories.tsx
  src/components/SideMenu/SideMenuItem/SideMenuItem.styles.tsx
  src/components/SideMenu/SideMenuItem/SideMenuItem.tsx
  src/components/SideMenu/SideMenuItem/index.tsx
  src/components/SideMenu/index.tsx
Labels: ✨ feature

#41 [feat] TopicDetailPage 기능 구현
  __mocks__/data/comment.ts
  __mocks__/data/topic.ts
  src/assets/user-default.png
  src/components/CommentForm/CommentForm.tsx
  src/components/CommentList/CommentList.tsx
  src/components/DefaultLayout/DefaultLayout.styles.tsx
  src/components/DefaultLayout/DefaultLayout.tsx
  src/components/Header/Header.style.tsx
  src/components/TopicDetailMain/TopicDetailMain.stories.tsx
  src/components/TopicDetailMain/TopicDetailMain.styles.tsx
  src/components/TopicDetailMain/TopicDetailMain.tsx
  src/components/TopicDetailMain/index.tsx
  src/components/TopicUserInfo/TopicUserInfo.stories.tsx
  src/components/TopicUserInfo/TopicUserInfo.styles.tsx
  src/components/TopicUserInfo/TopicUserInfo.tsx
  src/components/TopicUserInfo/index.tsx
  src/components/common/Grid/GridContainer.styles.tsx
  src/pages/_app.tsx
  src/pages/topic/[id].stories.tsx
  src/pages/topic/[id].tsx
Labels: ✨ feature

#43 [feat] 메인페이지 임시 구현
  __mocks__/data/member.ts
  __mocks__/data/topics.ts
  next.config.js
  src/assets/fonts/PoetsenOne-Regular.ttf
  src/components/DefaultLayout/DefaultLayout.styles.tsx
  src/components/MainTopicList/MainTopicList.stories.tsx
  src/components/MainTopicList/MainTopicList.style.tsx
  src/components/MainTopicList/MainTopicList.tsx
  src/components/MainTopicList/index.tsx
  src/components/TopicCard/SelectOption/SelectOption.tsx
  src/components/TopicCard/TopicCard.tsx
  src/components/TopicDetailMain/TopicDetailMain.styles.tsx
  src/components/TopicUserInfo/TopicUserInfo.styles.tsx
  src/pages/index.test.tsx
  src/pages/index.tsx
  src/styles/common.css
  src/styles/theme.ts
Labels: ✨ feature

#44 [feat] Topic 추가 버튼 UI 구현
  src/components/addButton/AddButton/AddButton.stories.tsx
  src/components/addButton/AddButton/AddButton.styles.tsx
  src/components/addButton/AddButton/AddButton.tsx
  src/components/addButton/AddButton/index.tsx
  src/components/addButton/FabButton/FabButton.stories.tsx
  src/components/addButton/FabButton/FabButton.styles.tsx
  src/components/addButton/FabButton/FabButton.tsx
  src/components/addButton/FabButton/index.tsx
Labels: ✨ feature

#49 [feat] 글쓰기 버튼 메인페이지에 추가
  src/components/main/FabButton/FabButton.styles.tsx
  src/components/main/MainTopicList/MainTopicList.style.tsx
  src/components/main/MainTopicList/MainTopicList.tsx
Labels: ✨ feature

#51 [feat] Topic 상세 페이지 msw 기반 api 연동
  .storybook/preview.js
  __mocks__/apis/browser.ts
  __mocks__/apis/handlers/comment.ts
  __mocks__/apis/handlers/index.ts
  __mocks__/apis/handlers/topic.ts
  __mocks__/apis/index.ts
  __mocks__/apis/sample.ts
  __mocks__/apis/server.ts
  __mocks__/data/comment.ts
  __mocks__/data/member.ts
  __mocks__/data/topic.ts
  package-lock.json
  package.json
  src/apis/comment.ts
  src/apis/index.ts
  src/apis/topic.ts
  src/components/topic/CommentList/CommentList.tsx
  src/components/topic/CommentList/CommentListItem/CommentListItem.tsx
  src/components/topic/TopicDetailMain/TopicDetailMain.stories.tsx
  src/components/topic/TopicDetailMain/TopicDetailMain.tsx
  src/components/topic/TopicUserInfo/TopicUserInfo.tsx
  src/configs/axios.ts
  src/pages/_app.tsx
  src/pages/topic/[id].stories.tsx
  src/pages/topic/[id].tsx
  src/queires/constant.ts
  src/queires/index.ts
  src/queires/useCreateComment.ts
  src/queires/useGetComments.ts
Labels: ✨ feature, ♻️ refactor

#54 [feat] 커먼성 Input 컴포넌트 기능 구현
  src/components/common/Input/Input.stories.tsx
  src/components/common/Input/Input.styles.tsx
  src/components/common/Input/Input.tsx
  src/components/common/Input/index.tsx
Labels: ✨ feature

#61 [feat] 커먼성 TextArea 컴포넌트 구현
  src/components/common/TextArea/TextArea.stories.tsx
  src/components/common/TextArea/TextArea.styles.tsx
  src/components/common/TextArea/TextArea.tsx
  src/components/common/TextArea/index.ts
Labels: ✨ feature

#66 [feat] 구글 oauth 로그인 기능 구현
  .env.sample
  .github/workflows/chromatic.yml
  .storybook/preview.js
  __mocks__/apis/handlers/auth.ts
  __mocks__/apis/handlers/index.ts
  src/apis/auth.ts
  src/apis/index.ts
  src/assets/icon/google_logo.svg
  src/assets/icon/index.tsx
  src/components/common/Header/Header.stories.tsx
  src/components/common/Header/Header.style.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Header/UserMenu/UserMenu.stories.tsx
  src/components/common/Header/UserMenu/UserMenu.styles.tsx
  src/components/common/Header/UserMenu/UserMenu.tsx
  src/components/common/Header/UserMenu/index.tsx
  src/components/common/SingleContentLayout/SingleContentLayout.stories.tsx
  src/components/common/SingleContentLayout/SingleContentLayout.styles.tsx
  src/components/common/SingleContentLayout/SingleContentLayout.tsx
  src/components/common/SingleContentLayout/index.tsx
  src/components/common/UserInfo/UserInfo.stories.tsx
  src/components/common/UserInfo/UserInfo.styles.tsx
  src/components/common/UserInfo/UserInfo.tsx
  src/components/common/UserInfo/index.tsx
  src/components/login/Login/Login.stories.tsx
  src/components/login/Login/Login.styles.tsx
  src/components/login/Login/Login.tsx
  src/components/login/Login/index.tsx
  src/configs/recoil.ts
  src/pages/_app.tsx
  src/pages/auth.ts
  src/pages/login/index.tsx
  src/pages/login/login.stories.tsx
  src/recoil/effects/localstorageEffect.ts
  src/recoil/userSession.ts
  src/styles/reset.css
Labels: ✨ feature
