Repository YAPP-Github/21st-Web-Team-2-FE, pull requests merged in 2023-02, with the labels that each got.

#77 [feat] 온보딩 및 회원가입 기능 구현
  __mocks__/apis/handlers/auth.ts
  src/apis/auth.ts
  src/assets/icon/designer.svg
  src/assets/icon/developer.svg
  src/assets/icon/index.tsx
  src/assets/icon/pm.svg
  src/components/common/SingleContentLayout/SingleContentLayout.styles.tsx
  src/components/onboarding/ContentFinish/ContentFinish.stories.tsx
  src/components/onboarding/ContentFinish/ContentFinish.styles.tsx
  src/components/onboarding/ContentFinish/ContentFinish.tsx
  src/components/onboarding/ContentFinish/index.tsx
  src/components/onboarding/ContentJob/ContentJob.stories.tsx
  src/components/onboarding/ContentJob/ContentJob.styles.tsx
  src/components/onboarding/ContentJob/ContentJob.tsx
  src/components/onboarding/ContentJob/index.tsx
  src/components/onboarding/ContentName/ContentName.stories.tsx
  src/components/onboarding/ContentName/ContentName.styles.tsx
  src/components/onboarding/ContentName/ContentName.tsx
  src/components/onboarding/ContentName/index.tsx
  src/components/onboarding/ContentYear/ContentYear.stories.tsx
  src/components/onboarding/ContentYear/ContentYear.styles.tsx
  src/components/onboarding/ContentYear/ContentYear.tsx
  src/components/onboarding/ContentYear/YearSelector/YearSelector.stories.tsx
  src/components/onboarding/ContentYear/YearSelector/YearSelector.styles.tsx
  src/components/onboarding/ContentYear/YearSelector/YearSelector.tsx
  src/components/onboarding/ContentYear/YearSelector/index.tsx
  src/components/onboarding/ContentYear/index.tsx
  src/components/onboarding/OnboardingLayout/OnboardingLayout.stories.tsx
  src/components/onboarding/OnboardingLayout/OnboardingLayout.styles.tsx
  src/components/onboarding/OnboardingLayout/OnboardingLayout.tsx
  src/components/onboarding/OnboardingLayout/index.tsx
  src/pages/auth.ts
  src/pages/onboarding/index.tsx
  src/pages/onboarding/onboarding.stories.tsx
  src/queires/useCheckNickname.ts
  src/queires/useSignup.ts
Labels: ✨ feature

#87 [feat] loading spinner UI 구현
  src/components/common/LoadingSpinner/LoadingSpinner.stories.tsx
  src/components/common/LoadingSpinner/LoadingSpinner.styles.tsx
  src/components/common/LoadingSpinner/LoadingSpinner.tsx
  src/components/common/LoadingSpinner/index.tsx
Labels: ✨ feature

#84 [feat] 회원가입, 로그인 과정 실제 API 연동
  src/apis/auth.ts
  src/components/onboarding/ContentFinish/ContentFinish.tsx
  src/components/onboarding/ContentJob/ContentJob.tsx
  src/components/onboarding/ContentName/ContentName.tsx
  src/components/onboarding/ContentYear/ContentYear.tsx
  src/pages/auth.ts
  src/pages/auth.tsx
  src/pages/onboarding/index.tsx
  src/queires/useSignin.ts
  src/queires/useSignup.ts
Labels: ✨ feature

#88 [feat] member api 적용 및 로그인 후 jwt 요청 구현
  .env.sample
  .github/workflows/chromatic.yml
  __mocks__/apis/handlers/member.ts
  __mocks__/data/member.ts
  src/apis/index.ts
  src/apis/member.ts
  src/components/common/Header/Header.tsx
  src/components/common/UserInfo/UserInfo.tsx
  src/components/main/Main/Main.tsx
  src/components/main/TopicCarousel/TopicCarousel.tsx
  src/configs/axios.ts
  src/constants/localstorage.ts
  src/pages/_app.tsx
  src/pages/topic/[id].tsx
  src/queires/useMember.ts
  src/queires/useProfile.ts
  src/recoil/userSession.ts
  src/utils/isServer.ts
Labels: 🐛bug, ✨ feature, ♻️ refactor

#96 [feat] 구글 oauth 과정 동안 loading UI 적용
  src/components/common/LoadingSpinner/LoadingSpinner.tsx
  src/pages/auth.tsx
Labels: ✨ feature

#97 [fix] 인기토픽 이미지/코드 제거
  src/components/common/TopicCard/TopicCard.tsx
  src/components/main/TopicCarousel/PopularTopicCard/PopularTopicCard.stories.tsx
  src/components/main/TopicCarousel/PopularTopicCard/PopularTopicCard.tsx
  src/components/main/TopicCarousel/PopularTopicCard/index.tsx
  src/components/main/TopicCarousel/TopicCarousel.tsx
Labels: 🐛bug, ✨ feature

#100 [fix] 로그인 관련 스토리 수정
  .storybook/preview.js
  src/components/common/Header/Header.stories.tsx
  src/components/common/Header/Header.tsx
  src/components/onboarding/ContentFinish/ContentFinish.stories.tsx
  src/components/onboarding/ContentJob/ContentJob.stories.tsx
  src/components/onboarding/ContentYear/ContentYear.stories.tsx
  src/queires/useMember.ts
  src/recoil/userSession.ts
Labels: 🐛bug

#101 [fix] 연차 데이터 형태 변경에 따른 타입 및 UI 변경
  __mocks__/data/member.ts
  src/components/topic/CommentList/CommentListItem/CommentListItem.tsx
  src/components/topic/TopicUserInfo/TopicUserInfo.tsx
  src/types/Member.ts
Labels: 🐛bug

#102 [fix] 코드 블럭 내용이 너무 짧을 때 대응
  __mocks__/data/voteOption.ts
  src/components/common/TopicCard/SelectOption/SelectOption.stories.tsx
  src/components/common/TopicCard/SelectOption/SelectOption.style.tsx
  src/components/common/TopicCard/TopicCard.stories.tsx
Labels: 🐛bug

#117 Feat/089 deploy
  .github/workflows/chromatic.yml
  next.config.js
  src/apis/auth.ts
  src/components/common/CodeEditor/languages.ts
  src/components/common/SelectButton/SelectButton.tsx
  src/components/login/Login/Login.tsx
  src/components/onboarding/ContentFinish/ContentFinish.tsx
  src/components/onboarding/ContentJob/ContentJob.tsx
  src/components/onboarding/ContentName/ContentName.tsx
  src/components/onboarding/ContentYear/ContentYear.tsx
  src/pages/_app.page.tsx
  src/pages/auth.page.tsx
  src/pages/index.page.tsx
  src/pages/index.stories.tsx
  src/pages/login/index.page.tsx
  src/pages/login/login.stories.tsx
  src/pages/onboarding/index.page.tsx
  src/pages/onboarding/onboarding.stories.tsx
  src/pages/topic/[id].page.tsx
  src/pages/topic/[id].stories.tsx
  src/pages/write/WritePage.stories.tsx
  src/pages/write/index.page.tsx
  src/queires/useSignup.ts
Labels: ♻️ refactor, 🎉 release

#104 [feat] 투표하기 기능 api 추가
  __mocks__/apis/handlers/index.ts
  __mocks__/apis/handlers/topic.ts
  __mocks__/apis/handlers/vote.ts
  src/apis/index.ts
  src/apis/vote.ts
  src/components/common/TopicCard/SelectOption/SelectOption.tsx
  src/components/common/TopicCard/TopicCard.stories.tsx
  src/components/common/TopicCard/TopicCard.tsx
  src/queires/useVote.ts
Labels: ✨ feature

#119 [feat] 코드블록 랜더링 방식 변경
  src/components/common/TopicCard/SelectOption/SelectOption.style.tsx
  src/components/common/TopicCard/SelectOption/SelectOption.tsx
  src/components/common/TopicCard/TopicCard.stories.tsx
  src/components/common/TopicCard/TopicCard.styles.tsx
  src/components/common/TopicCard/TopicCard.tsx
Labels: ✨ feature

#118 [feat] 직무 분야 디자인에 맞게 수정
  __mocks__/data/member.ts
  src/assets/icon/default.svg
  src/assets/icon/index.tsx
  src/assets/user-default.png
  src/components/common/ProfileImg/ProfileImg.stories.tsx
  src/components/common/ProfileImg/ProfileImg.tsx
  src/components/common/UserInfo/UserInfo.tsx
  src/components/onboarding/ContentFinish/ContentFinish.stories.tsx
  src/components/onboarding/ContentFinish/ContentFinish.tsx
  src/components/onboarding/ContentJob/ContentJob.tsx
  src/components/onboarding/ContentYear/ContentYear.stories.tsx
  src/components/onboarding/ContentYear/ContentYear.tsx
  src/types/Member.ts
Labels: ✨ feature

#120 [feat] 메인 페이지 api 체크
  src/apis/topic.ts
  src/components/main/Main/Main.styles.tsx
  src/components/main/Main/Main.tsx
  src/components/main/MainTopicList/MainTopicList.stories.tsx
  src/components/main/MainTopicList/MainTopicList.tsx
  src/components/main/SideMenu/SideMenu.tsx
  src/components/main/SideMenu/SideMenuItem/SideMenuItem.tsx
  src/pages/index.page.tsx
  src/queires/useGetTopics.ts
Labels: ✨ feature

#122 [feat] storybook에서 localStorage 관리
  .storybook/localStorageDecorator.ts
  .storybook/preview.js
  __mocks__/data/localStorage.ts
  src/pages/index.stories.tsx
  src/pages/topic/[id].stories.tsx
  src/pages/write/WritePage.stories.tsx
Labels: ✨ feature

#137 [feat] 구글 oauth 로그인 실패시 UX 구현
  src/pages/auth.page.tsx
Labels: ✨ feature

#126 [feat] 화면 최소 넓이 지정
  src/components/common/TopicCard/TopicCard.styles.tsx
  src/styles/common.css
Labels: ✨ feature

#134 [feat] 토픽 좋아요 기능 구현
  __mocks__/apis/handlers/topic.ts
  src/apis/topic.ts
  src/components/common/Icon/Icon.tsx
  src/components/common/TopicCard/TopicCard.stories.tsx
  src/components/common/TopicCard/TopicCard.styles.tsx
  src/components/common/TopicCard/TopicCard.tsx
  src/hooks/useAuthCheck.ts
  src/queires/useLikeTopic.ts
Labels: ✨ feature

#145 [feat] favicon 등록
  public/favicon.ico
  src/pages/_document.page.tsx
Labels: ✨ feature

#143 [feat] 토픽 내용 공유시 meta 정보(Open Graph) 나오게 하기
  package-lock.json
  package.json
  public/og.png
  src/components/common/SEO/SEO.tsx
  src/components/common/SEO/index.tsx
  src/pages/index.page.tsx
  src/pages/topic/[id].page.tsx
Labels: ✨ feature

#141 [feat] 문의하기 누를 시 문의할 수 있는 google form 으로 이동
  src/components/common/Header/UserMenu/UserMenu.styles.tsx
  src/components/common/Header/UserMenu/UserMenu.tsx
  src/constants/link.ts
Labels: ✨ feature

#149 [fix] TopicCardProps 오류 해결
  src/components/common/TopicCard/TopicCard.tsx
Labels: 🐛bug

#152 [feat] 토픽 상세 페이지에서 로그인 여부에 따른 기능 동작 구현 - 서버 연동
  __mocks__/apis/handlers/comment.ts
  src/apis/comment.ts
  src/components/topic/TopicDetailMain/TopicDetailMain.tsx
  src/queires/useCreateComment.ts
Labels: ✨ feature, ♻️ refactor

#158 [feat] 로그인 약관 링크 추가
  src/components/login/Login/Login.styles.tsx
  src/components/login/Login/Login.tsx
  src/constants/link.ts
Labels: ✨ feature

#153 [feat] 로그아웃 기능 구현
  __mocks__/apis/handlers/auth.ts
  src/apis/auth.ts
  src/components/common/Header/Header.tsx
  src/queires/useLogout.ts
Labels: ✨ feature

#157 [fix] ssr 방식에서 header.authorization이 적용되지 않던 문제 해결
  .storybook/cookieDecorator.ts
  .storybook/localStorageDecorator.ts
  .storybook/preview.js
  __mocks__/data/cookie.ts
  __mocks__/data/localStorage.ts
  src/apis/topic.ts
  src/components/common/Header/Header.stories.tsx
  src/configs/axios.ts
  src/constants/index.ts
  src/pages/auth.page.tsx
  src/pages/index.page.tsx
  src/pages/index.stories.tsx
  src/pages/topic/[id].page.tsx
  src/pages/topic/[id].stories.tsx
  src/pages/write/WritePage.stories.tsx
  src/recoil/effects/cookieEffect.ts
  src/recoil/userSession.ts
  src/utils/auth.ts
  src/utils/cookie.ts
Labels: 🐛bug, ♻️ refactor

#161 [feat] image api 적용
  __mocks__/apis/handlers/image.ts
  __mocks__/apis/handlers/index.ts
  next.config.js
  src/apis/image.ts
  src/apis/index.ts
  src/components/common/ImgSelector/ImgSelector.tsx
  src/components/write/WriteMain/VoteOptionInputs/VoteOptionInputs.tsx
  src/queires/useUploadImage.ts
Labels: ✨ feature

#165 [fix] 온보딩 과정(회원가입)에서 완료하지 않고 새로고침 후 진행하면 회원가입 실패
  src/pages/auth.page.tsx
Labels: 🐛bug

#169 [fix] 글쓰기 페이지 디자인 오류 수정
  src/components/write/WriteMain/WriteMain.styles.tsx
Labels: 🐛bug

#168 [fix] 잘못된 토큰으로 요청했을 때의 처리
  .storybook/preview.js
  src/apis/topic.ts
  src/configs/axios.ts
  src/pages/_app.page.tsx
Labels: 🐛bug

#170 [refactor] 로그인 검증 공통 로직 분리
  src/components/common/TopicCard/TopicCard.stories.tsx
  src/components/common/TopicCard/TopicCard.tsx
  src/components/main/Main/Main.tsx
  src/hooks/useAuthCheck.ts
  src/pages/write/index.page.tsx
Labels: ♻️ refactor

#167 [feat] 시각화 기능 추가
  __mocks__/data/voteOption.ts
  src/assets/icon/guitar.svg
  src/assets/icon/index.tsx
  src/components/common/TopicCard/SelectOption/SelectOption.style.tsx
  src/components/common/TopicCard/SelectOption/SelectOption.tsx
  src/components/common/TopicCard/TopicCard.stories.tsx
  src/components/common/TopicCard/TopicCard.tsx
  src/components/common/TopicCard/VoteStatistics/VoteStatistics.stories.tsx
  src/components/common/TopicCard/VoteStatistics/VoteStatistics.style.tsx
  src/components/common/TopicCard/VoteStatistics/VoteStatistics.tsx
  src/components/common/TopicCard/VoteStatistics/index.tsx
  src/types/VoteOption.ts
Labels: ✨ feature

#172 [fix] 프로필 이미지 오류 해결
  src/components/common/TopicCard/TopicCard.tsx
  src/components/topic/CommentList/CommentListItem/CommentListItem.styles.tsx
  src/components/topic/CommentList/CommentListItem/CommentListItem.tsx
  src/pages/_app.page.tsx
Labels: 🐛bug

#174 [fix] 글쓰기 페이지 이동 오류 해결
  src/hooks/useAuthCheck.ts
  src/pages/write/index.page.tsx
Labels: 🐛bug

#177 [fix] 메인 페이지 투표 오류 해결
  src/components/common/TopicCard/TopicCard.tsx
Labels: 🐛bug

#180 [fix] onboarding error 수정
  src/apis/member.ts
  src/queires/useMember.ts
Labels: 🐛bug

#181 [feat] 댓글 좋아요 기능 구현
  __mocks__/apis/handlers/comment.ts
  src/apis/comment.ts
  src/components/topic/CommentList/CommentListItem/CommentListItem.styles.tsx
  src/components/topic/CommentList/CommentListItem/CommentListItem.tsx
  src/queires/useLikeComment.ts
Labels: ✨ feature

#182 [docs] 인기 태그 임시로 추가
  src/components/main/SideMenu/SideMenu.tsx
Labels: 📝 docs

#186 [fix] 댓글 프로필 사진 오류 해결
  src/components/topic/CommentList/CommentListItem/CommentListItem.styles.tsx
  src/components/topic/CommentList/CommentListItem/CommentListItem.tsx
Labels: 🐛bug

#187 [fix] 쿠키를 모두 루트에서 관리하도록 변경
  src/utils/cookie.ts
Labels: 🐛bug

#184 [feat] 로그아웃 시 새로고침
  src/components/common/Header/Header.tsx
Labels: ✨ feature
